apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-springboot-demo
  labels:
    app: k8s-springboot-demo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-springboot-demo
  template:
    metadata:
      labels:
        app: k8s-springboot-demo
    spec:
      containers:
        - name: k8s-springboot-demo
          image: demo:1.1
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
          imagePullPolicy: IfNotPresent
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-springboot-demo
  namespace: default
  labels:
    app: k8s-springboot-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: k8s-springboot-demo
  type: NodePort
